name: build

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - "scripts/*"
              - "src/*.ts"
              - "styles/*.ts"
              - "themes/*.ts"
              - "vite.config.ts"
              - "package.json"

      - name: Build theme
        id: build
        if: steps.changes.outputs.src == 'true'
        run: |
          npm install
          npm run build
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Upload css assets
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: themes
          path: dist/*.css

      - name: Upload templates assets
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: templates
          path: templates
